## 2023
# Tourist Flow Simulation in GAMA Using Historical Data Parameters
- id: doi:10.1007/978-3-031-25752-0_27
  tags: 
    - ABM
    - Tourism
    - Geo-simulation

## 2022
- id: doi:10.5194/ica-abs-5-68-2022
  image: images/dialect_lemma.png
  date: 2022-9-14
  tags: 
    - Linked Data
    - Digital Humanities
    - Dialect
    - GeoAI
  extra-links:
    - type: source
      link: https://github.com/Geoinfo-TUGraz/UI4Dialect
      text: Source

# Symbolic and subsymbolic GeoAI : Geospatial knowledge graphs and spatially explicit machine learning
- id: doi:10.1111/tgis.13012
  
# How Many Equations of Motion Describe a Moving Human?
- id: arxiv:2207.14331v2
  authors:
      - Gabriele De Luca
      - Thomas J. Lampoltshammer
      - Johannes Scholz

# Deep-Learning vs Regression: Prediction of Tourism Flow with Limited Data
- id: doi:10.48550/arXiv.2206.13274

# A Literature Review on the Usage of Agent-Based Modelling to Study Policies for Managing International Migration
- id: doi:10.3390/socsci11080356

# Data-driven Tourism for Sustainability: The Role of Transdisciplinarity and Computational Social Sciences in Tourist Studies Programs
#- title: Data-driven Tourism for Sustainability: The Role of Transdisciplinarity and Computational Social Sciences in Tourist Studies Programs
#  authors:
#    - Thomas J. Lampoltshammer
#    - Johannes Scholz
#    - Stefanie Wallinger
#  publisher: Proceedings of CloudEarth Conference 2022 
#  date: 2022-05-18
#  link: https://conference.cloudearthi.com/wp-content/uploads/2022/05/ID_8.pdf
  
# Geospatial Artificial Intelligence und Geoinformatik: neue Paradigmen in der räumlichen Analyse
#- title: Geospatial Artificial Intelligence und Geoinformatik: neue Paradigmen in der räumlichen Analyse
#  authors:
#    - Johannes Scholz
#  publisher: GeoNews
#  date: 2022-01-01
#  link: https://www.rmdatagroup.com/aktuelles/geonews/geonews-2-2022/#c15759
  
# Off-Road Navigation Maps for Robotic Platforms using Convolutional Neural Networks
- id: doi:10.5194/agile-giss-3-55-2022

#Optimising Antenna Positioning for Maximum Coverage: The Case Study of Cattle Tracking in Austrian Alps Using Long Range (LoRa) Based Monitoring System
- id: doi:10.1007/978-3-031-06245-2_6

# Platial mobility: expanding place and mobility in GIS via platio-temporal representations and the mobilities paradigm
- id: doi:10.1007/s10109-022-00389-3

# Point Patterns of Historical Landmarks in the Valley of Mexico
- id: doi:10.5194/agile-giss-3-33-2022

# Research Directions for Merging Geospatial Technologies with Smart Manufacturing Systems
- id: doi:10.1520/SSMS20220004

# The AMADEE-20 Robotic Exploration Cascade: An Experience Report
- id: doi:10.1007/978-3-031-04870-8_56

# The Intersection between GIScience and History: an Overview of an Emerging Scientific Field
- id: doi:10.5194/agile-giss-3-48-2022

## 2021
# Simulating the forest fuel market as a socio‐ecological system with spatial agent‐based methods: A case study in Carinthia, Austria
- id: doi:10.1111/nrm.12291

#A Prototypical Geospatial Knowledge Graph And Spatio-Temporal Question Answering for Supply Chain Visibility
- id: doi:10.25436/E2JS3V

#Eco-friendly Routing based on real-time Air-quality Sensor Data from Vehicles
- id: doi:10.25436/E23W2G

#Spatial Linked Data Approach for Trace Data in Digital Humanities
- id: doi:10.25436/E2T882

##2020
#Evaluating Geo-Tagged Twitter Data to Analyze Tourist Flows in Styria, Austria
- id: doi:10.3390/ijgi9110681

#Merging Geospatial Technologies with Cross Reality in the Context of Smart Manufacturing Systems
- id: doi:10.1109/ISMAR-Adjunct51615.2020.00093

#Agent-Based Simulation for Indoor Manufacturing Environments---Evaluating the Effects of Spatialization
- id: doi:10.1007/978-3-030-14745-7_17

#An Approach to Decompose and Evaluate a Complex GIS-Application Design to a Simple, Lightweight, User-Centered App-Based Design Using User Experience Evaluation
- id: doi:10.3390/ijgi9090505
