- id: doi:10.5194/ica-abs-5-68-2022
  image: images/dialect_lemma.png
  date: 2022-9-14
  tags: 
    - Linked Data
    - Digital Humanities
    - Dialect
    - GeoAI
  extra-links:
    - type: source
      link: https://github.com/Geoinfo-TUGraz/UI4Dialect
      text: Source
      
- id: doi:10.1007/978-3-031-25752-0_27
  image: 
  date: 2023-01-15
  tags: 
    - ABM
    - Tourism
    - Geo-simulation
    
- id: doi:10.1111/tgis.13012
  date: 2022-12-18

# Deep-Learning vs Regression: Prediction of Tourism Flow with Limited Data
- id: doi:10.48550/arXiv.2206.13274
  image:
  date: 2022-06-27
